### PR TITLE
Story/406866 add exp optional param

### PR DESCRIPTION
**Pull request by matt-yin-lf**
- Added an optimal parameter `expireInSeconds` with a default value of 3600.
  - If `expireInSeconds` == 0, the JWT (authorization key) will not have `exp` kvp
  - If `expireInSeconds` <0, an error will be thrown
- Added tests for the feature above
- Updated `CHANGELOG.md` and release version

### CODE REVIEW

**Review by terrencejames-lf — COMMENTED** [review]
Could you revert the whitespace changes?

**Comment by matt-yin-lf** [comment]
> 

Whitespace and indent reverted

**Comment by terrencejames-lf** [comment]
Could you also link this to an issue?

**Comment by matt-yin-lf** [comment]
> Could you also link this to an issue?

Issue linked

**Review by terrencejames-lf — APPROVED** [review]

**Pull request merged**
